set number                      "Line numbers are good
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom

" no idea what these do; from my old vimrc
set ai
set hlsearch
set ruler
highlight Comment ctermfg=green

set termguicolors

set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

filetype plugin on
filetype indent on

" if file is changed from different program
set autoread

syntax enable

set noswapfile

set clipboard=unnamed

filetype plugin indent on
syntax on

" enables scrolling in vim in tmux
set mouse=a
